-- MySQL Script generated by MySQL Workbench
-- Sat Dec 26 23:42:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`libraries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`libraries` ;

CREATE TABLE IF NOT EXISTS `mydb`.`libraries` (
  `id` INT NOT NULL,
  `borrowingperiod` INT NOT NULL,
  `visible` TINYINT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_libraries_users1_idx` (`users_id` ASC) VISIBLE,
  UNIQUE INDEX `users_id_UNIQUE` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_libraries_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`books` ;

CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `isbn` VARCHAR(255) NULL,
  `available` TINYINT NOT NULL,
  `availablefrom` DATE NULL,
  `libraries_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_books_libraries1_idx` (`libraries_id` ASC) VISIBLE,
  CONSTRAINT `fk_books_libraries1`
    FOREIGN KEY (`libraries_id`)
    REFERENCES `mydb`.`libraries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bookrent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bookrent` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bookrent` (
  `id` INT NOT NULL,
  `ownerid` INT NOT NULL,
  `startdate` DATE NOT NULL,
  `enddate` DATE NOT NULL,
  `archive` TINYINT NOT NULL,
  `books_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bookrent_books1_idx` (`books_id` ASC) VISIBLE,
  INDEX `fk_bookrent_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_bookrent_books1`
    FOREIGN KEY (`books_id`)
    REFERENCES `mydb`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookrent_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chat` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`messages` ;

CREATE TABLE IF NOT EXISTS `mydb`.`messages` (
  `id` INT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `text` TEXT(1000) NOT NULL,
  `chat_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_messages_chat1_idx` (`chat_id` ASC) VISIBLE,
  INDEX `fk_messages_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_messages_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `mydb`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tags` (
  `id` INT NOT NULL,
  `text` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books_has_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`books_has_tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`books_has_tags` (
  `tags_id` INT NOT NULL,
  `books_id` INT NOT NULL,
  PRIMARY KEY (`tags_id`, `books_id`),
  INDEX `fk_tags_has_books_books1_idx` (`books_id` ASC) VISIBLE,
  INDEX `fk_tags_has_books_tags_idx` (`tags_id` ASC) VISIBLE,
  CONSTRAINT `fk_tags_has_books_tags`
    FOREIGN KEY (`tags_id`)
    REFERENCES `mydb`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_has_books_books1`
    FOREIGN KEY (`books_id`)
    REFERENCES `mydb`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_has_chat` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users_has_chat` (
  `users_id` INT NOT NULL,
  `chat_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `chat_id`),
  INDEX `fk_users_has_chat_chat1_idx` (`chat_id` ASC) VISIBLE,
  INDEX `fk_users_has_chat_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_chat_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_chat_chat1`
    FOREIGN KEY (`chat_id`)
    REFERENCES `mydb`.`chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
