-- MySQL Script generated by MySQL Workbench
-- Mon Dec 28 20:30:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
                                              `id` INT NOT NULL,
                                              `first_name` VARCHAR(255) NOT NULL,
                                              `surname` VARCHAR(255) NOT NULL,
                                              `email` VARCHAR(255) NOT NULL,
                                              `password` VARCHAR(255) NOT NULL,
                                              `role` VARCHAR(255) NOT NULL,
                                              PRIMARY KEY (`id`),
                                              UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`libraries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`libraries` ;

CREATE TABLE IF NOT EXISTS `mydb`.`libraries` (
                                                  `id` INT NOT NULL,
                                                  `borrowing_period` INT NOT NULL,
                                                  `visible` TINYINT NOT NULL,
                                                  `user_id` INT NOT NULL,
                                                  PRIMARY KEY (`id`),
                                                  INDEX `fk_libraries_users1_idx` (`user_id` ASC) VISIBLE,
                                                  UNIQUE INDEX `users_id_UNIQUE` (`user_id` ASC) VISIBLE,
                                                  CONSTRAINT `fk_libraries_users1`
                                                      FOREIGN KEY (`user_id`)
                                                          REFERENCES `mydb`.`users` (`id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`books` ;

CREATE TABLE IF NOT EXISTS `mydb`.`books` (
                                              `id` INT NOT NULL,
                                              `title` VARCHAR(255) NOT NULL,
                                              `author` VARCHAR(255) NOT NULL,
                                              `isbn` VARCHAR(255) NULL,
                                              `available` TINYINT NOT NULL,
                                              `available_from` DATE NULL,
                                              `library_id` INT NOT NULL,
                                              PRIMARY KEY (`id`),
                                              INDEX `fk_books_libraries1_idx` (`library_id` ASC) VISIBLE,
                                              CONSTRAINT `fk_books_libraries1`
                                                  FOREIGN KEY (`library_id`)
                                                      REFERENCES `mydb`.`libraries` (`id`)
                                                      ON DELETE NO ACTION
                                                      ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bookrents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bookrents` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bookrents` (
                                                  `id` INT NOT NULL,
                                                  `owner_id` INT NOT NULL,
                                                  `start_date` DATE NOT NULL,
                                                  `end_date` DATE NOT NULL,
                                                  `archive` TINYINT NOT NULL,
                                                  `book_id` INT NOT NULL,
                                                  `user_id` INT NOT NULL,
                                                  PRIMARY KEY (`id`),
                                                  INDEX `fk_bookrent_books1_idx` (`book_id` ASC) VISIBLE,
                                                  INDEX `fk_bookrent_users1_idx` (`user_id` ASC) VISIBLE,
                                                  CONSTRAINT `fk_bookrent_books1`
                                                      FOREIGN KEY (`book_id`)
                                                          REFERENCES `mydb`.`books` (`id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION,
                                                  CONSTRAINT `fk_bookrent_users1`
                                                      FOREIGN KEY (`user_id`)
                                                          REFERENCES `mydb`.`users` (`id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chats` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chats` (
                                              `id` INT NOT NULL,
                                              `title` VARCHAR(255) NOT NULL,
                                              PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`messages` ;

CREATE TABLE IF NOT EXISTS `mydb`.`messages` (
                                                 `id` INT NOT NULL,
                                                 `time_stamp` DATETIME NOT NULL,
                                                 `text` TEXT(1000) NOT NULL,
                                                 `chat_id` INT NOT NULL,
                                                 `user_id` INT NOT NULL,
                                                 PRIMARY KEY (`id`),
                                                 INDEX `fk_messages_chat1_idx` (`chat_id` ASC) VISIBLE,
                                                 INDEX `fk_messages_users1_idx` (`user_id` ASC) VISIBLE,
                                                 CONSTRAINT `fk_messages_chat1`
                                                     FOREIGN KEY (`chat_id`)
                                                         REFERENCES `mydb`.`chats` (`id`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION,
                                                 CONSTRAINT `fk_messages_users1`
                                                     FOREIGN KEY (`user_id`)
                                                         REFERENCES `mydb`.`users` (`id`)
                                                         ON DELETE NO ACTION
                                                         ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tags` (
                                             `id` INT NOT NULL,
                                             `text` VARCHAR(255) NOT NULL,
                                             PRIMARY KEY (`id`),
                                             UNIQUE INDEX `text_UNIQUE` (`text` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`books_tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`books_tags` (
                                                   `books_id` INT NOT NULL,
                                                   `tags_id` INT NOT NULL,
                                                   PRIMARY KEY (`books_id`, `tags_id`),
                                                   INDEX `fk_tags_has_books_books1_idx` (`books_id` ASC) VISIBLE,
                                                   INDEX `fk_tags_has_books_tags_idx` (`tags_id` ASC) VISIBLE,
                                                   CONSTRAINT `fk_tags_has_books_tags`
                                                       FOREIGN KEY (`tags_id`)
                                                           REFERENCES `mydb`.`tags` (`id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION,
                                                   CONSTRAINT `fk_tags_has_books_books1`
                                                       FOREIGN KEY (`books_id`)
                                                           REFERENCES `mydb`.`books` (`id`)
                                                           ON DELETE NO ACTION
                                                           ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chats_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chats_users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chats_users` (
                                                    `chats_id` INT NOT NULL,
                                                    `users_id` INT NOT NULL,
                                                    PRIMARY KEY (`chats_id`, `users_id`),
                                                    INDEX `fk_users_has_chat_chat1_idx` (`chats_id` ASC) VISIBLE,
                                                    INDEX `fk_users_has_chat_users1_idx` (`users_id` ASC) VISIBLE,
                                                    CONSTRAINT `fk_users_has_chat_users1`
                                                        FOREIGN KEY (`users_id`)
                                                            REFERENCES `mydb`.`users` (`id`)
                                                            ON DELETE NO ACTION
                                                            ON UPDATE NO ACTION,
                                                    CONSTRAINT `fk_users_has_chat_chat1`
                                                        FOREIGN KEY (`chats_id`)
                                                            REFERENCES `mydb`.`chats` (`id`)
                                                            ON DELETE NO ACTION
                                                            ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Drop table `mydb`.`hibernate_sequence` if was created
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hibernate_sequence`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
